
name: Manual Maven Build and Release

on:
  workflow_dispatch: # Triggered manually

jobs:
  build:
    name: Build with Maven
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 18
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '18'

    - name: Build with Maven
      run: mvn -B clean install
      
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: jar
        path: target/*-with-dependencies.jar

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: jar
        path: target/

    - name: Get tag name
      id: tag
      run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body: |
          Release of the project.
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/*-with-dependencies.jar
        asset_name: ManuscriptAssistant-${{ github.ref_name }}.jar
        asset_content_type: application/java-archive
